nice test results

diff --git a/.github/workflows/deploy-pages.yml b/.github/workflows/deploy-pages.yml
--- a/.github/workflows/deploy-pages.yml
+++ b/.github/workflows/deploy-pages.yml
@@ -40,7 +40,12 @@ jobs:
         run: pnpm build
       - name: Test
         working-directory: ./protocol
-        run: pnpm test
+        run: pnpm ci
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "./protocol/junit.xml"
 
   build-app:
     runs-on: ubuntu-latest
